### ISSUE TITLE
wrong CIDR

### ISSUE THREAD

**Issue by DanielRuf** [addiscent/ip-addr-to-arin-cidr#1]
this gives the CIDR of the network which is often allocated to an organization like RIPE and is not the right CIDR

https://github.com/ckthomaston/ip-addr-to-arin-cidr/blob/7652c8c7c84745a26be685e037950cbf190ca2ce/ipaddr-to-cidr-worker.php#L61

compare the following results:
http://whois.arin.net/rest/ip/78.30.192.0 (this IP belongs to Lancom Ltd)
http://www.fastix.org/netztools/?addr=78.30.192.0&action=whois
http://bgp.he.net/ip/78.30.192.0#_whois

**Comment by addiscent** [comment]
Agreed, the ARIN Who-is database search result CIDR does not match the other more accurate results noted in this issue.

**Comment by addiscent** [comment]
Greetings,

Agreed, the ARIN Who-is database search result CIDR does not match the 
other more accurate results noted in this issue.

Thanks for bringing this to my attention.

On 04/09/2015 02:31 AM, Daniel Ruf wrote:

> this gives the CIDR of the network which is often allocated to an 
> organization like RIPE and is not the right CIDR
> 
> https://github.com/ckthomaston/ip-addr-to-arin-cidr/blob/7652c8c7c84745a26be685e037950cbf190ca2ce/ipaddr-to-cidr-worker.php#L61
> 
> compare the following results:
> http://whois.arin.net/rest/ip/78.30.192.0 (this IP belongs to Lancom Ltd)
> http://www.fastix.org/netztools/?addr=78.30.192.0&action=whois
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/ckthomaston/ip-addr-to-arin-cidr/issues/1.

## 

  Best Regards,
-    Charles Thomaston
  *DalorWeb LLC
  http://dalorweb.com http://dalorweb.com/

**Comment by DanielRuf** [comment]
I think the RIPE API gives the best and complete results including the inetnum (IP range)

http://rest.db.ripe.net/search.json?query-string=78.30.192.0
http://rest.db.ripe.net/search.xml?query-string=78.30.192.0

**Comment by addiscent** [comment]
Thanks for this information.  I am saturated with other work, but I will try to take a look at it, when I have time.

**Comment by DanielRuf** [comment]
You are welcome. No hurry. Okay, thanks.
