### ISSUE TITLE
demo not available

### ISSUE THREAD

**Issue by DanielRuf** [addiscent/ip-addr-to-arin-cidr#2]
it seems your website and the demo are not available anymore

**Comment by addiscent** [comment]
I investigated, and DalorWeb. (dalorweb.com), and DalorWeb Tools, (dwt.dalorweb.com), are both reachable.  I did discover a broken link on the home page of DalorWeb Tools, and repaired it.  I also followed the link given in the README.md of this repository.  It is functional.  So, I'm at a loss for how to reproduce this issue.  Can you enlighten me on how to reproduce it?

**Comment by addiscent** [comment]
Greetings,

Thanks for your comment.

I investigated, and DalorWeb. (dalorweb.com), and DalorWeb Tools, 
(dwt.dalorweb.com), are both reachable. I did discover a broken link on 
the home page of DalorWeb Tools, which references the Deny From IP page 
on that web site, (based on ip-addr-to-arin-cidr repository code), and I 
just finished repairing it.

I also followed the link given in the README.md of the 
ip-addr-to-arin-cidr repository, which points to the 
http://ip-addr-to-arin-cidr.dalorweb.com demo. It is functional, for me. 
So, I'm at a loss for how to reproduce this issue. Can you enlighten me 
on how to reproduce it?

IIRC, I did move the Deny From IP demo to 
http://ip-addr-to-arin-cidr.dalorweb.com, from 
http://ip-addr-to-arin-cidr.dalornet.com, a few months ago.  In addition 
to the README.md file in the github repo, are you perhaps using a link 
about which I have forgotten?

Thanks for your time.

On 04/09/2015 02:31 AM, Daniel Ruf wrote:

> it seems your website and the demo are not available anymore
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/ckthomaston/ip-addr-to-arin-cidr/issues/2.

## 

  Best Regards,
-    Charles Thomaston
  *DalorWeb LLC
  http://dalorweb.com http://dalorweb.com/

**Comment by DanielRuf** [comment]
this says 403 forbidden:
http://ip-addr-to-arin-cidr.dalorweb.com/

Do you use some IP blocking solution or something else?
I try to access the website from Germany but I just get the 403. Same from two different networks from Germany (two different providers)

http://www.fastix.org/netztools/?addr=http%3A%2F%2Fwww.dalorweb.com%2F&action=wget
http://www.webpagetest.org/result/150409_FT_12BD/1/details/

**Comment by addiscent** [comment]
Greetings,

Thanks for your timely reply.

I had inadvertently blocked access to my web site for some IP address 
ranges.  Hoisted by my own petard, as they say.

I fixed that error a few minutes ago.  You should have access to the web 
site now.  I am keen to know you are able to access three URLs in 
particular.

```
 http://ip-addr-to-arin-cidr.dalorweb.com/
 http://dalorweb.com
 http://dwt.dalorweb.com
```

I have no way of verifying the correction fixed the issue, as it worked 
for me before, so if you still get an error 403, please let me know.

By the way, issue #1, still has not been addressed.

Thanks for bringing this to my attention, I appreciate your time.

On 04/09/2015 10:47 AM, Daniel Ruf wrote:

> this says 403 forbidden:
> http://ip-addr-to-arin-cidr.dalorweb.com/
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/ckthomaston/ip-addr-to-arin-cidr/issues/2#issuecomment-91307447.

## 

  Best Regards,
-    Charles Thomaston
  *DalorWeb LLC
  http://dalorweb.com http://dalorweb.com/

**Comment by DanielRuf** [comment]
Thanks, I can access the website now.

**Comment by addiscent** [comment]
Thanks for letting me know my fixes worked.

On 04/10/2015 12:18 AM, Daniel Ruf wrote:

> Thanks, I can access the website now.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/ckthomaston/ip-addr-to-arin-cidr/issues/2#issuecomment-91461165.

## 

  Best Regards,
-    Charles Thomaston
  *DalorWeb LLC
  http://dalorweb.com http://dalorweb.com/
